# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_auto_20170220_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
