# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postuservisiblemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostUserVisibleManager',
        ),
    ]
