# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_delete_postuservisiblemanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_vaisible',
            new_name='is_visible',
        ),
    ]
